// Mock data for the application
// This file contains all the mock data used throughout the app

export const mockProducts = [
  {
    id: 1,
    name: 'RoboClean Pro X1',
    category: 'Robot Cleaners',
    tagline: 'The smartest way to clean your home',
    price: 599.99,
    originalPrice: 799.99,
    discount: 25,
    rating: 4.8,
    reviews: 1250,
    image: '🧹',
    badge: 'Best Seller',
    badgeVariant: 'success',
    description: 'Experience the future of home cleaning with RoboClean Pro X1. Featuring advanced AI navigation, powerful 3000Pa suction, and smart mapping technology.',
    stock: 45,
    inStock: true,
    aiPowered: true,
    voiceControl: true,
    appControl: true,
    autoCharging: true,
    smartMapping: true,
    scheduling: true,
    batteryLife: '3 hours',
    warranty: '2 Years',
    keyFeatures: [
      'Advanced AI-powered navigation system',
      '3000Pa powerful suction for deep cleaning',
      'Smart mapping with multi-floor support',
      'Voice control via Alexa, Google Assistant, and Siri',
      'Mobile app with real-time monitoring',
      'Automatic return to charging dock',
      'HEPA filter for allergen capture',
      'Ultra-quiet operation at 55dB',
    ],
    features: ['AI Navigation', '3000Pa Suction', 'Smart Mapping'],
  },
  {
    id: 2,
    name: 'ChefBot Deluxe',
    category: 'Kitchen Robots',
    tagline: 'Your personal cooking assistant',
    price: 1299.99,
    rating: 4.9,
    reviews: 890,
    image: '👨‍🍳',
    badge: 'New Arrival',
    badgeVariant: 'primary',
    description: 'Automated cooking with 500+ recipe database. ChefBot handles everything from chopping to cooking with precision.',
    stock: 23,
    inStock: true,
    aiPowered: true,
    voiceControl: true,
    appControl: true,
    scheduling: true,
    batteryLife: 'N/A (Plugged)',
    warranty: '2 Years',
    keyFeatures: [
      '500+ pre-programmed recipes',
      'Automatic ingredient recognition',
      'Precise temperature control',
      'Voice-guided cooking instructions',
      'Self-cleaning system',
      'Mobile app with custom recipes',
    ],
    features: ['500+ Recipes', 'Voice Control', 'App Integration'],
  },
  {
    id: 3,
    name: 'LawnMaster AI',
    category: 'Lawn Care',
    tagline: 'Smart lawn care made simple',
    price: 799.99,
    rating: 4.7,
    reviews: 650,
    image: '🌱',
    badge: 'Top Rated',
    badgeVariant: 'warning',
    description: 'Smart lawn mowing with weather adaptation. GPS navigation ensures perfect coverage every time.',
    stock: 34,
    inStock: true,
    aiPowered: true,
    appControl: true,
    smartMapping: true,
    scheduling: true,
    batteryLife: '4 hours',
    warranty: '2 Years',
    keyFeatures: [
      'GPS-guided navigation',
      'Weather adaptive scheduling',
      'Multi-zone management',
      'Rain sensor technology',
      'Adjustable cutting height',
      'Anti-theft GPS tracking',
    ],
    features: ['Weather Adaptive', 'GPS Navigation', 'Rain Sensor'],
  },
  {
    id: 4,
    name: 'ServeBot Elite',
    category: 'Service Robots',
    tagline: 'Autonomous serving assistant',
    price: 899.99,
    rating: 4.6,
    reviews: 420,
    image: '🍽️',
    badge: 'Featured',
    badgeVariant: 'purple',
    description: 'Autonomous food and drink serving assistant. Perfect for restaurants, cafes, and home parties.',
    stock: 18,
    inStock: true,
    aiPowered: true,
    appControl: true,
    batteryLife: '8 hours',
    warranty: '2 Years',
    keyFeatures: [
      'Multi-floor navigation',
      '5kg tray capacity',
      'Obstacle avoidance system',
      'Voice announcements',
      'Automatic docking',
      'UV sanitization tray',
    ],
    features: ['Obstacle Avoidance', 'Tray Capacity 5kg', 'Multi-floor'],
  },
  {
    id: 5,
    name: 'RoboClean Max',
    category: 'Robot Cleaners',
    tagline: 'Maximum power, maximum clean',
    price: 699.99,
    originalPrice: 799.99,
    discount: 12,
    rating: 4.7,
    reviews: 890,
    image: '🧹',
    badge: 'Best Value',
    badgeVariant: 'success',
    description: 'Enhanced suction with 4000Pa power. Perfect for pet owners with HEPA filtration.',
    stock: 52,
    inStock: true,
    aiPowered: true,
    voiceControl: true,
    appControl: true,
    autoCharging: true,
    smartMapping: true,
    batteryLife: '3.5 hours',
    warranty: '2 Years',
    keyFeatures: [
      '4000Pa suction power',
      'HEPA H13 filter',
      'Pet hair specialist',
      'Carpet boost mode',
      'Virtual no-go zones',
      'Multi-room mapping',
    ],
    features: ['4000Pa Suction', 'HEPA Filter', 'Pet Hair Specialist'],
  },
  {
    id: 6,
    name: 'SmartMop Pro',
    category: 'Robot Cleaners',
    tagline: 'Vacuum and mop in one',
    price: 449.99,
    rating: 4.5,
    reviews: 654,
    image: '🧼',
    description: 'Vacuum and mop in one device. 2-in-1 cleaning solution with smart water control.',
    stock: 67,
    inStock: true,
    aiPowered: true,
    appControl: true,
    autoCharging: true,
    batteryLife: '2.5 hours',
    warranty: '1 Year',
    keyFeatures: [
      '2-in-1 vacuum and mop',
      'Smart water control',
      'Auto carpet detection',
      '300ml water tank',
      'App-controlled zones',
    ],
    features: ['2-in-1 Design', 'Water Tank 300ml', 'Auto Return'],
  },
];

export const mockCategories = [
  { id: 1, name: 'Robot Cleaners', description: 'Automated cleaning robots', productCount: 12, icon: '🧹' },
  { id: 2, name: 'Kitchen Robots', description: 'Smart cooking assistants', productCount: 8, icon: '👨‍🍳' },
  { id: 3, name: 'Lawn Care', description: 'Automated lawn maintenance', productCount: 6, icon: '🌱' },
  { id: 4, name: 'Service Robots', description: 'Food and beverage service', productCount: 10, icon: '🍽️' },
  { id: 5, name: 'Smart Home', description: 'Home automation devices', productCount: 9, icon: '🏠' },
];

export const mockReviews = [
  {
    id: 1,
    productId: 1,
    productName: 'RoboClean Pro X1',
    author: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    avatar: '👩',
    rating: 5,
    title: 'Absolutely Amazing Product!',
    content: 'This robot has completely transformed my daily cleaning routine. The AI navigation is incredibly smart, and it never misses a spot. Highly recommend!',
    date: '2024-01-15',
    verified: true,
    helpful: 45,
    notHelpful: 2,
    images: ['📷', '📷', '📷'],
    status: 'approved',
  },
  {
    id: 2,
    productId: 2,
    productName: 'ChefBot Deluxe',
    author: 'Michael Chen',
    email: 'michael.c@email.com',
    avatar: '👨',
    rating: 4,
    title: 'Great value for money',
    content: 'Very impressed with the build quality and performance. Setup was easy and the robot is quite efficient. Battery life could be better.',
    date: '2024-01-10',
    verified: true,
    helpful: 32,
    notHelpful: 1,
    images: [],
    status: 'approved',
  },
  {
    id: 3,
    productId: 1,
    productName: 'RoboClean Pro X1',
    author: 'Emily Rodriguez',
    email: 'emily.r@email.com',
    avatar: '👩‍🦰',
    rating: 5,
    title: 'Perfect for pet owners!',
    content: 'I have two dogs and this robot handles pet hair like a champ! The suction power is impressive.',
    date: '2024-01-05',
    verified: true,
    helpful: 28,
    notHelpful: 0,
    images: ['📷'],
    status: 'approved',
  },
];

export const mockMessages = [
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@email.com',
    subject: 'Product Inquiry',
    message: 'Hi, I\'m interested in the RoboClean Pro X1. Does it work well on hardwood floors?',
    date: '2024-01-15 10:30 AM',
    status: 'unread',
    priority: 'normal',
    starred: false,
  },
  {
    id: 2,
    name: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    subject: 'Shipping Question',
    message: 'I placed an order yesterday (Order #12345). Can you tell me when it will be shipped?',
    date: '2024-01-15 09:15 AM',
    status: 'read',
    priority: 'high',
    starred: true,
  },
];

export const mockOrders = [
  {
    id: 'ORD-001',
    customer: 'John Doe',
    product: 'RoboClean Pro',
    amount: 599.99,
    status: 'Completed',
    date: '2024-01-15',
  },
  {
    id: 'ORD-002',
    customer: 'Jane Smith',
    product: 'ChefBot Deluxe',
    amount: 1299.99,
    status: 'Processing',
    date: '2024-01-15',
  },
];

export default {
  mockProducts,
  mockCategories,
  mockReviews,
  mockMessages,
  mockOrders,
};